Repository JIITODC/jiitodc.github.io, pull requests merged in 2018-10, with the labels that each got.

#73 Added info to the how we started section
  index.html
Labels: requires review

#80 Updated PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: top priority, under discussion

#79 Updated issue template
  .github/ISSUE_TEMPLATE.md
Labels: top priority, under discussion

#87 Spelling and grammar
  index.html
Labels: incorrect format
